[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Michael Dai", email = "mikdai@ucdavis.edu"},
]
dependencies = [
    "django>=4.1.5",
    "gunicorn>=20.1.0",
]
requires-python = ">=3.11"
