# Generated by Django 4.1.5 on 2023-05-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scratchorgs', '0002_organization_alias_organization_expired_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='access_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='access_url',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dev_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scratchorgs.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='login_url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
