# Generated by Django 4.1.5 on 2023-05-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratchorgs', '0003_alter_organization_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='namespace',
            field=models.CharField(default='', max_length=15),
        ),
    ]
